import { Memory } from "../types";
import { SPEECH_TREE } from "../constants";

export const generateHtmlReport = (memory: Memory): string => {
  const baseline = memory.baseline;
  const tasks = memory.speechTasks || [];
  
  // Calculate aggregate stats
  const totalPractice = tasks.reduce((acc, t) => acc + t.attempts, 0);
  const wordsMastered = tasks.filter(t => t.status === 'mastered').length;

  const baselineRows = baseline?.results.map(r => `
    <tr class="${r.isCorrect ? 'correct' : 'incorrect'}">
      <td><strong>${r.word}</strong></td>
      <td>${r.phoneme}</td>
      <td>${r.isCorrect ? '✅ Yes' : '❌ No'}</td>
      <td>${r.notes}</td>
    </tr>
  `).join('') || '<tr><td colspan="4">No baseline data available.</td></tr>';

  const taskRows = tasks.map(t => `
    <tr>
      <td>${t.word}</td>
      <td>${t.targetPhoneme || '-'}</td>
      <td>${t.status}</td>
      <td>${t.attempts}</td>
      <td>${t.report?.strengths || '-'}</td>
      <td>${t.report?.needsWork || '-'}</td>
    </tr>
  `).join('');

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Teddy Talk - Speech Progress Report</title>
  <style>
    body { font-family: sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; background: #f9f9f9; }
    h1 { color: #d97706; border-bottom: 2px solid #d97706; padding-bottom: 10px; }
    h2 { color: #b45309; margin-top: 30px; }
    .card { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin-bottom: 20px; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; }
    th, td { text-align: left; padding: 12px; border-bottom: 1px solid #eee; }
    th { background-color: #f3f4f6; color: #666; font-size: 0.9em; text-transform: uppercase; }
    .correct { background-color: #ecfdf5; }
    .incorrect { background-color: #fef2f2; }
    .summary-box { background: #fffbeb; border: 1px solid #fcd34d; padding: 15px; border-radius: 8px; }
    .stat-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 10px; }
    .stat-item { background: #f0f9ff; padding: 15px; border-radius: 8px; text-align: center; }
    .stat-val { font-size: 24px; font-weight: bold; color: #0284c7; }
    .footer { margin-top: 50px; font-size: 0.8em; color: #999; text-align: center; }
  </style>
</head>
<body>
  <h1>🧸 Teddy Talk Report</h1>
  <p><strong>Child Name:</strong> ${memory.childName || 'Unknown'}</p>
  <p><strong>Report Date:</strong> ${new Date().toLocaleDateString()}</p>

  <div class="card">
    <h2>Overview</h2>
    <div class="stat-grid">
      <div class="stat-item">
        <div class="stat-val">${baseline?.recommendedStartingPoint || 'N/A'}</div>
        <div>Recommended Level</div>
      </div>
      <div class="stat-item">
        <div class="stat-val">${wordsMastered}</div>
        <div>Words Mastered</div>
      </div>
      <div class="stat-item">
        <div class="stat-val">${totalPractice}</div>
        <div>Total Practice Attempts</div>
      </div>
    </div>
  </div>

  <div class="card">
    <h2>Baseline Assessment</h2>
    ${baseline ? `<div class="summary-box"><strong>AI Summary:</strong> ${baseline.summary}</div>` : ''}
    <table>
      <thead>
        <tr>
          <th>Word</th>
          <th>Phoneme</th>
          <th>Correct?</th>
          <th>Notes</th>
        </tr>
      </thead>
      <tbody>
        ${baselineRows}
      </tbody>
    </table>
  </div>

  <div class="card">
    <h2>Practice History</h2>
    <table>
      <thead>
        <tr>
          <th>Word</th>
          <th>Sound</th>
          <th>Status</th>
          <th>Attempts</th>
          <th>Strengths</th>
          <th>Needs Work</th>
        </tr>
      </thead>
      <tbody>
        ${taskRows}
      </tbody>
    </table>
  </div>
  
  <div class="footer">
    Generated by Teddy Talk AI. Not a medical diagnosis.
  </div>
</body>
</html>
  `;
};
